<script lang="ts">
    import { ExternalLink } from "../common";
  </script>
  
    <p>
      This shows <ExternalLink
        href="https://wiki.openstreetmap.org/wiki/Tag:railway%3Dstation"
      >
        railway station
      </ExternalLink> data from OpenStreetMap.
    </p>
  
    <p>
      License: <ExternalLink href="https://www.openstreetmap.org/copyright">
        Open Data Commons Open Database License
      </ExternalLink>
    </p>
  