interface defaultsAndOptionsForCrossingType {
    at_road_junction: defaultAndOptionsForCrossingTypeAndContext,
    at_side_road: defaultAndOptionsForCrossingTypeAndContext,
    stand_alone: defaultAndOptionsForCrossingTypeAndContext,
}

interface defaultAndOptionsForCrossingTypeAndContext {
    is_signalised: defaultAndOptions,
    pedestrians_have_priority_over_traffic: defaultAndOptions,
    cyclists_have_priority_over_traffic: defaultAndOptions,
    has_pedestrian_refuge: defaultAndOptions,
    setback_from_junction: defaultAndOptions,
    has_raised_table: defaultAndOptions,
    has_buildout: defaultAndOptions,
    has_detectors_to_hold_traffic: defaultAndOptions,
    has_tactile_paving: defaultAndOptions,
    has_dropped_kerbs: defaultAndOptions,
    safe_to_cross_indicated_by_visual_aids: defaultAndOptions,
    safe_to_cross_indicated_by_audio: defaultAndOptions,
    safe_to_cross_indicated_by_rotating_cone: defaultAndOptions,
    includes_place_making_pocket_park: defaultAndOptions,
    includes_place_making_social_space: defaultAndOptions,
    includes_place_making_greening: defaultAndOptions,
    includes_place_making_community_garden: defaultAndOptions,
    includes_place_making_wayfinding: defaultAndOptions,
    includes_place_making_art: defaultAndOptions,
    includes_place_making_landscaping: defaultAndOptions,
    includes_place_making_other: defaultAndOptions,
    junction_has_tight_radii: defaultAndOptions,
    permitted_movements_at_side_road_junctions: defaultAndOptions,
    is_continuous_footway: defaultAndOptions,
    fulfils_single_movement_desire_line: defaultAndOptions,
    fulfils_routing_desire: defaultAndOptions,
    provides_connection_to_bus_stop: defaultAndOptions,
}

export interface defaultAndOptions {
    existsForThisJunctionType: boolean,
    isDefaulted: boolean,
    options: string[],
    defaultValue: string,
}

const yesNoOptions = ["yes", "no", ""];

const markedPriorityOptionsAndDefaults: defaultsAndOptionsForCrossingType = {
    at_road_junction: {
        is_signalised: {
            existsForThisJunctionType: true,
            isDefaulted: true,
            options: yesNoOptions,
            defaultValue: "no",
        },
        pedestrians_have_priority_over_traffic: {
            existsForThisJunctionType: true,
            isDefaulted: false,
            options: yesNoOptions,
            defaultValue: "",
        },
        cyclists_have_priority_over_traffic: {
            existsForThisJunctionType: true,
            isDefaulted: false,
            options: yesNoOptions,
            defaultValue: "",
        },
        has_pedestrian_refuge: {
            existsForThisJunctionType: false,
            isDefaulted: false,
            options: yesNoOptions,
            defaultValue: "",
        },
        setback_from_junction: {
            existsForThisJunctionType: true,
            isDefaulted: false,
            options: ["fully_setback", "not_setback", "partially_setback", ""],
            defaultValue: "",
        },
        has_raised_table: {
            existsForThisJunctionType: true,
            isDefaulted: false,
            options: yesNoOptions,
            defaultValue: "",
        },
        has_buildout: {
            existsForThisJunctionType: true,
            isDefaulted: false,
            options: yesNoOptions,
            defaultValue: "",
        },
        has_detectors_to_hold_traffic: {
            existsForThisJunctionType: false,
            isDefaulted: false,
            options: yesNoOptions,
            defaultValue: "",
        },
        has_tactile_paving: {
            existsForThisJunctionType: true,
            isDefaulted: false,
            options: yesNoOptions,
            defaultValue: "",
        },
        has_dropped_kerbs: {
            existsForThisJunctionType: true,
            isDefaulted: false,
            options: yesNoOptions,
            defaultValue: "",
        },
        safe_to_cross_indicated_by_visual_aids: {
            existsForThisJunctionType: false,
            isDefaulted: false,
            options: yesNoOptions,
            defaultValue: "",
        },
        safe_to_cross_indicated_by_audio: {
            existsForThisJunctionType: false,
            isDefaulted: false,
            options: yesNoOptions,
            defaultValue: "",
        },
        safe_to_cross_indicated_by_rotating_cone: {
            existsForThisJunctionType: false,
            isDefaulted: false,
            options: yesNoOptions,
            defaultValue: "",
        },
        includes_place_making_pocket_park: {
            existsForThisJunctionType: true,
            isDefaulted: false,
            options: yesNoOptions,
            defaultValue: "",
        },
        includes_place_making_social_space: {
            existsForThisJunctionType: true,
            isDefaulted: false,
            options: yesNoOptions,
            defaultValue: "",
        },
        includes_place_making_greening: {
            existsForThisJunctionType: true,
            isDefaulted: false,
            options: yesNoOptions,
            defaultValue: "",
        },
        includes_place_making_community_garden: {
            existsForThisJunctionType: true,
            isDefaulted: false,
            options: yesNoOptions,
            defaultValue: "",
        },
        includes_place_making_wayfinding: {
            existsForThisJunctionType: true,
            isDefaulted: false,
            options: yesNoOptions,
            defaultValue: "",
        },
        includes_place_making_art: {
            existsForThisJunctionType: true,
            isDefaulted: false,
            options: yesNoOptions,
            defaultValue: "",
        },
        includes_place_making_landscaping: {
            existsForThisJunctionType: true,
            isDefaulted: false,
            options: yesNoOptions,
            defaultValue: "",
        },
        includes_place_making_other: {
            existsForThisJunctionType: true,
            isDefaulted: false,
            options: yesNoOptions,
            defaultValue: "",
        },
        junction_has_tight_radii: {
            existsForThisJunctionType: false,
            isDefaulted: false,
            options: yesNoOptions,
            defaultValue: "",
        },
        permitted_movements_at_side_road_junctions: {
            existsForThisJunctionType: false,
            isDefaulted: false,
            options: yesNoOptions,
            defaultValue: "",
        },
        is_continuous_footway: {
            existsForThisJunctionType: false,
            isDefaulted: false,
            options: yesNoOptions,
            defaultValue: "",
        },
        fulfils_single_movement_desire_line: {
            existsForThisJunctionType: false,
            isDefaulted: false,
            options: yesNoOptions,
            defaultValue: "",
        },
        fulfils_routing_desire: {
            existsForThisJunctionType: false,
            isDefaulted: false,
            options: yesNoOptions,
            defaultValue: "",
        },
        provides_connection_to_bus_stop: {
            existsForThisJunctionType: false,
            isDefaulted: false,
            options: yesNoOptions,
            defaultValue: "",
        }
    },
    at_side_road: {
        is_signalised: undefined,
        pedestrians_have_priority_over_traffic: undefined,
        cyclists_have_priority_over_traffic: undefined,
        has_pedestrian_refuge: undefined,
        setback_from_junction: undefined,
        has_raised_table: undefined,
        has_buildout: undefined,
        has_detectors_to_hold_traffic: undefined,
        has_tactile_paving: undefined,
        has_dropped_kerbs: undefined,
        safe_to_cross_indicated_by_visual_aids: undefined,
        safe_to_cross_indicated_by_audio: undefined,
        safe_to_cross_indicated_by_rotating_cone: undefined,
        includes_place_making_pocket_park: undefined,
        includes_place_making_social_space: undefined,
        includes_place_making_greening: undefined,
        includes_place_making_community_garden: undefined,
        includes_place_making_wayfinding: undefined,
        includes_place_making_art: undefined,
        includes_place_making_landscaping: undefined,
        includes_place_making_other: undefined,
        junction_has_tight_radii: undefined,
        permitted_movements_at_side_road_junctions: undefined,
        is_continuous_footway: undefined,
        fulfils_single_movement_desire_line: undefined,
        fulfils_routing_desire: undefined,
        provides_connection_to_bus_stop: undefined
    },
    stand_alone: {
        is_signalised: undefined,
        pedestrians_have_priority_over_traffic: undefined,
        cyclists_have_priority_over_traffic: undefined,
        has_pedestrian_refuge: undefined,
        setback_from_junction: undefined,
        has_raised_table: undefined,
        has_buildout: undefined,
        has_detectors_to_hold_traffic: undefined,
        has_tactile_paving: undefined,
        has_dropped_kerbs: undefined,
        safe_to_cross_indicated_by_visual_aids: undefined,
        safe_to_cross_indicated_by_audio: undefined,
        safe_to_cross_indicated_by_rotating_cone: undefined,
        includes_place_making_pocket_park: undefined,
        includes_place_making_social_space: undefined,
        includes_place_making_greening: undefined,
        includes_place_making_community_garden: undefined,
        includes_place_making_wayfinding: undefined,
        includes_place_making_art: undefined,
        includes_place_making_landscaping: undefined,
        includes_place_making_other: undefined,
        junction_has_tight_radii: undefined,
        permitted_movements_at_side_road_junctions: undefined,
        is_continuous_footway: undefined,
        fulfils_single_movement_desire_line: undefined,
        fulfils_routing_desire: undefined,
        provides_connection_to_bus_stop: undefined
    },
}
